apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: curl
  name: curl
spec:
  containers:
  - image: curlimages/curl
    name: curl
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 100Mi
    command:
      - sh
      - -c
      - sleep 3600
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
