kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        apiServer:
          extraArgs:
            "enable-admission-plugins": "MutatingAdmissionWebhook,ValidatingAdmissionWebhook"
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
            authorization-mode: "AlwaysAllow"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP